project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!local/"

execute:
  freeze: auto  # re-render only when source changes

website:
  title: "Meta-analysis Workshop"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/stat-teaching/csameta2024
        aria-label: GitHub
        
author: 
  - name: "Filippo Gambarota"
    email: filippo.gambarota@unipd.it
    twitter: fgambarota
    github: filippogambarota
    orcid: "0000-0002-6666-1747"
  - name: "Gianmarco Altoè"
    email: gianmarco.altoè@unipd.it
    orcid: "0000-0003-1154-9528"
institute: "University of Padova"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
